admins:
- 383323360693583874
- 505777481333342218
- 249526667125587968
content: Hey, ich m?chte dich gerne zu etwas einladen, ich hoffe du kannst dir diese
  kurze Nachricht trotzdem durchlesen. Ich betreibe einen DC Server, der bald verschiedene
  Minecraft Projekte zur Auswahl hat und brauche daf?r mehr Streamer, damit wir alle
  eine gr??ere & erfolgreiche Community aufbauen k?nnen. Ich freue mich auf eine R?ckmeldung!
  Fragen darfst du gerne stellen. MfG, EinfachMxrc
twitch_oauth: oauth:xgjn83e1ufgkusad63v243r48uqp7n
